# Generated by Django 4.2.4 on 2023-11-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_publicacao_delete_produto_alter_usuario_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacao',
            old_name='id_publicao',
            new_name='id_publicacao',
        ),
    ]
