# Generated by Django 4.2.4 on 2023-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fab', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
