# Generated by Django 4.2.4 on 2023-10-26 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_usuario_remove_produto_id_produto_id_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
